name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    environment: Test  # This is the name of the environment to deploy to

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env
          echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env
          echo "SNOWTRACE_API_KEY=${{ secrets.SNOWTRACE_API_KEY }}" >> .env
          echo "COINMARKETCAP_API_KEY=${{ secrets.COINMARKETCAP_API_KEY }}" >> .env
          echo "INFURA_API_KEY=${{ secrets.INFURA_API_KEY }}" >> .env
          echo "DATAHUB_API_KEY=${{ secrets.DATAHUB_API_KEY }}" >> .env
          echo "REPORT_GAS=${{ secrets.REPORT_GAS }}" >> .env
          echo "EVM_LOGGING=${{ secrets.EVM_LOGGING }}" >> .env
          echo "DEPLOYER_PK=${{ secrets.DEPLOYER_PK }}" >> .env
          echo "TOKEN_OWNER_PK=${{ secrets.TOKEN_OWNER_PK }}" >> .env
          echo "PROD_DEPLOYER_PK=${{ secrets.PROD_DEPLOYER_PK }}" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Generate documentation
        run: npx hardhat docgen

      - name: Run tests
        run: npx hardhat test

      # # Deploy to Polygon Mumbai if tests pass
      # - name: Deploy to Polygon Mumbai
      #   run: npx hardhat deploy --network polygonMumbai

      # ... (previous steps)

      # Deploy to Polygon Mumbai if tests pass
      - name: Deploy to Polygon Mumbai
        id: deploy
        run: |
          OUTPUT=$(npx hardhat deploy --network polygonMumbai)
          echo "$OUTPUT"
          echo "::set-output name=deploy-output::$OUTPUT"

      # Update deployments.md with new addresses
      - name: Update DEPLOYMENTS.md
        run: |
          OUTPUT="${{ steps.deploy.outputs.deploy-output }}"
          echo "## Deployments on Polygon Mumbai" >> DEPLOYMENTS.md
          echo "\n" >> DEPLOYMENTS.md
          # Handle "reusing" output format
          echo "$OUTPUT" | grep "reusing" | while read -r line ; do
            CONTRACT_NAME=$(echo $line | awk -F'"' '{print $2}')
            CONTRACT_ADDRESS=$(echo $line | awk '{print $NF}')
            echo "- **$CONTRACT_NAME**: $CONTRACT_ADDRESS" >> DEPLOYMENTS.md
          done
          # Handle "deploying" output format
          echo "$OUTPUT" | grep "deploying" | while read -r line ; do
            CONTRACT_NAME=$(echo $line | awk -F'"' '{print $2}')
            CONTRACT_ADDRESS=$(echo $line | awk '{print $10}')
            echo "- **$CONTRACT_NAME**: $CONTRACT_ADDRESS" >> DEPLOYMENTS.md
          done

      # Commit and push the updated deployments.md
      - name: Commit and push DEPLOYMENTS.md
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DEPLOYMENTS.md
          git commit -m "Update DEPLOYMENTS.md with new contract addresses"
          git push
